from __future__ import annotations

import argparse
import math
import re
import sys
import threading
import time
from pathlib import Path

import ifcopenshell
import ifcopenshell.geom
import ifcopenshell.util.unit


def safe_name(value: object, fallback: str) -> str:
    text = str(value or fallback).strip()
    text = re.sub(r"\s+", "_", text)
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", text)
    return text.strip("_.-") or fallback


def material_color(material: object) -> tuple[float, float, float, float]:
    transparency = float(getattr(material, "transparency", 0.0) or 0.0)
    alpha = 1.0 - transparency if math.isfinite(transparency) else 1.0

    try:
        color = material.get_color()
        return float(color.r()), float(color.g()), float(color.b()), alpha
    except Exception:
        pass

    diffuse = getattr(material, "diffuse", None)
    if diffuse is not None:
        try:
            return float(diffuse.r()), float(diffuse.g()), float(diffuse.b()), alpha
        except Exception:
            pass

        try:
            colour = diffuse.colour
            return float(colour.Red), float(colour.Green), float(colour.Blue), alpha
        except Exception:
            try:
                values = list(diffuse)
                if len(values) >= 3:
                    return float(values[0]), float(values[1]), float(values[2]), alpha
            except Exception:
                pass

    return 0.8, 0.8, 0.8, 1.0


def write_mtl(path: Path, materials: dict[str, tuple[float, float, float, float]]) -> None:
    lines: list[str] = ["# Generated by ifc_to_obj.py"]
    for name, color in materials.items():
        r, g, b, alpha = color
        lines.extend(
            [
                "",
                f"newmtl {name}",
                f"Kd {r:.6f} {g:.6f} {b:.6f}",
                f"Ka {r * 0.2:.6f} {g * 0.2:.6f} {b * 0.2:.6f}",
                "Ks 0.050000 0.050000 0.050000",
                "Ns 10.000000",
                f"d {alpha:.6f}",
            ]
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ifc_unit_scale(model: ifcopenshell.file) -> float:
    try:
        scale = float(ifcopenshell.util.unit.calculate_unit_scale(model))
        return scale if math.isfinite(scale) and scale > 0.0 else 1.0
    except Exception:
        return 1.0


def make_settings(weld_vertices: bool) -> ifcopenshell.geom.settings:
    settings = ifcopenshell.geom.settings()
    settings.set("use-world-coords", True)
    settings.set("weld-vertices", weld_vertices)
    return settings


def calculate_xy_alignment_angle(
    model: ifcopenshell.file,
    *,
    threads: int,
    weld_vertices: bool,
    scale: float,
    progress_callback: object | None = None,
) -> float:
    iterator = ifcopenshell.geom.iterator(make_settings(weld_vertices), model, threads)
    if not iterator.initialize():
        raise RuntimeError("No geometry was found in the IFC file")

    count = 0
    sum_x = 0.0
    sum_y = 0.0
    sum_xx = 0.0
    sum_xy = 0.0
    sum_yy = 0.0
    shape_count = 0

    while True:
        shape_count += 1
        if progress_callback and shape_count % 25 == 1:
            progress_callback(f"Calculating model direction... {shape_count} elements")
        verts = list(iterator.get().geometry.verts)
        for index in range(0, len(verts), 3):
            x = verts[index] * scale
            y = verts[index + 1] * scale
            count += 1
            sum_x += x
            sum_y += y
            sum_xx += x * x
            sum_xy += x * y
            sum_yy += y * y
        if not iterator.next():
            break

    if count < 2:
        return 0.0

    mean_x = sum_x / count
    mean_y = sum_y / count
    cov_xx = (sum_xx / count) - (mean_x * mean_x)
    cov_xy = (sum_xy / count) - (mean_x * mean_y)
    cov_yy = (sum_yy / count) - (mean_y * mean_y)

    principal_angle = 0.5 * math.atan2(2.0 * cov_xy, cov_xx - cov_yy)
    return -principal_angle


def rotate_xy(x: float, y: float, angle: float) -> tuple[float, float]:
    if angle == 0.0:
        return x, y
    cos_angle = math.cos(angle)
    sin_angle = math.sin(angle)
    return (x * cos_angle) - (y * sin_angle), (x * sin_angle) + (y * cos_angle)


def calculate_bbox(
    model: ifcopenshell.file,
    *,
    threads: int,
    weld_vertices: bool,
    scale: float,
    rotation: float,
    progress_callback: object | None = None,
) -> tuple[list[float], list[float]]:
    iterator = ifcopenshell.geom.iterator(make_settings(weld_vertices), model, threads)
    if not iterator.initialize():
        raise RuntimeError("No geometry was found in the IFC file")

    minimum = [float("inf"), float("inf"), float("inf")]
    maximum = [float("-inf"), float("-inf"), float("-inf")]
    shape_count = 0
    while True:
        shape_count += 1
        if progress_callback and shape_count % 25 == 1:
            progress_callback(f"Checking size and position... {shape_count} elements")
        verts = list(iterator.get().geometry.verts)
        for index in range(0, len(verts), 3):
            x, y = rotate_xy(verts[index] * scale, verts[index + 1] * scale, rotation)
            z = verts[index + 2] * scale
            values = (x, y, z)
            for axis, value in enumerate(values):
                minimum[axis] = min(minimum[axis], value)
                maximum[axis] = max(maximum[axis], value)
        if not iterator.next():
            break

    return minimum, maximum


def origin_offset(
    minimum: list[float],
    maximum: list[float],
    mode: str,
) -> tuple[float, float, float]:
    if mode == "center":
        return tuple(-((maximum[axis] + minimum[axis]) / 2.0) for axis in range(3))
    if mode == "min":
        return tuple(-minimum[axis] for axis in range(3))
    return 0.0, 0.0, 0.0


def convert_ifc_to_obj(
    ifc_path: Path,
    obj_path: Path,
    *,
    threads: int = 1,
    weld_vertices: bool = True,
    scale: float | None = None,
    origin: str = "center",
    align_xy: bool = True,
    progress_callback: object | None = None,
    object_callback: object | None = None,
) -> tuple[int, int, int]:
    if progress_callback:
        progress_callback("Loading IFC file...")
    model = ifcopenshell.open(str(ifc_path))
    output_scale = ifc_unit_scale(model) if scale is None else scale
    if progress_callback:
        progress_callback("Checking units...")
    rotation = (
        calculate_xy_alignment_angle(
            model,
            threads=threads,
            weld_vertices=weld_vertices,
            scale=output_scale,
            progress_callback=progress_callback,
        )
        if align_xy
        else 0.0
    )
    if progress_callback and not align_xy:
        progress_callback("Keeping the original direction.")

    minimum, maximum = calculate_bbox(
        model,
        threads=threads,
        weld_vertices=weld_vertices,
        scale=output_scale,
        rotation=rotation,
        progress_callback=progress_callback,
    )
    offset = origin_offset(minimum, maximum, origin)
    if progress_callback:
        progress_callback("Writing OBJ/MTL files...")

    iterator = ifcopenshell.geom.iterator(make_settings(weld_vertices), model, threads)
    if not iterator.initialize():
        raise RuntimeError(f"No geometry was found in {ifc_path}")

    obj_path.parent.mkdir(parents=True, exist_ok=True)
    mtl_path = obj_path.with_suffix(".mtl")
    materials: dict[str, tuple[float, float, float, float]] = {}

    vertex_offset = 1
    object_count = 0
    vertex_count = 0
    face_count = 0
    previous_material: str | None = None

    with obj_path.open("w", encoding="utf-8", newline="\n") as obj:
        obj.write("# Generated by ifc_to_obj.py\n")
        obj.write(f"# scale {output_scale:.12g}\n")
        obj.write(f"# align_xy {str(align_xy).lower()}\n")
        obj.write(f"# rotation_z_degrees {math.degrees(rotation):.12g}\n")
        obj.write(f"# origin {origin}\n")
        obj.write(f"# offset {offset[0]:.12g} {offset[1]:.12g} {offset[2]:.12g}\n")
        obj.write(f"# bounds_min {minimum[0]:.12g} {minimum[1]:.12g} {minimum[2]:.12g}\n")
        obj.write(f"# bounds_max {maximum[0]:.12g} {maximum[1]:.12g} {maximum[2]:.12g}\n")
        obj.write(f"mtllib {mtl_path.name}\n\n")

        while True:
            shape = iterator.get()
            geometry = shape.geometry
            verts = list(geometry.verts)
            faces = list(geometry.faces)

            if verts and faces:
                object_count += 1
                product = getattr(shape, "product", None)
                type_name = safe_name(product.is_a() if product else None, "IfcProduct")
                product_name = safe_name(getattr(shape, "name", None), f"shape_{object_count}")
                guid = safe_name(getattr(shape, "guid", None), str(getattr(shape, "id", object_count)))
                obj.write(f"o {type_name}_{product_name}_{guid}\n")
                if object_callback:
                    entity = model.by_id(int(shape.id))
                    object_callback(f"{type_name}_{product_name}_{guid}", {
                        'ifc_id': entity.id(), 'global_id': getattr(entity, 'GlobalId', ''),
                        'ifc_class': entity.is_a(), 'name': getattr(entity, 'Name', '') or '',
                        'description': getattr(entity, 'Description', '') or '',
                        'object_type': getattr(entity, 'ObjectType', '') or '',
                        'tag': getattr(entity, 'Tag', '') or '',
                    })

                for index in range(0, len(verts), 3):
                    x, y = rotate_xy(verts[index] * output_scale, verts[index + 1] * output_scale, rotation)
                    x += offset[0]
                    y += offset[1]
                    z = (verts[index + 2] * output_scale) + offset[2]
                    obj.write(f"v {x:.9g} {y:.9g} {z:.9g}\n")

                source_materials = list(geometry.materials)
                material_ids = list(geometry.material_ids)
                shape_material_names: list[str] = []
                for material_index, material in enumerate(source_materials):
                    raw_name = getattr(material, "name", None) or f"material_{material_index}"
                    material_name = safe_name(raw_name, f"material_{material_index}")
                    shape_material_names.append(material_name)
                    materials.setdefault(material_name, material_color(material))

                default_material = "default"
                materials.setdefault(default_material, (0.8, 0.8, 0.8, 1.0))

                for face_index in range(0, len(faces), 3):
                    triangle_index = face_index // 3
                    material_name = default_material
                    if triangle_index < len(material_ids) and shape_material_names:
                        material_id = material_ids[triangle_index]
                        if 0 <= material_id < len(shape_material_names):
                            material_name = shape_material_names[material_id]
                    if material_name != previous_material:
                        obj.write(f"usemtl {material_name}\n")
                        previous_material = material_name

                    a = faces[face_index] + vertex_offset
                    b = faces[face_index + 1] + vertex_offset
                    c = faces[face_index + 2] + vertex_offset
                    obj.write(f"f {a} {b} {c}\n")

                obj.write("\n")
                vertex_offset += len(verts) // 3
                vertex_count += len(verts) // 3
                face_count += len(faces) // 3
                if progress_callback and object_count % 25 == 1:
                    progress_callback(f"Writing OBJ... {object_count} elements")

            if not iterator.next():
                break

    write_mtl(mtl_path, materials)
    if progress_callback:
        progress_callback("Conversion completed.")
    return object_count, vertex_count, face_count
